### ISSUE TITLE
Vulnerability Report-Account Takeover via Password Reset Functionality

### ISSUE THREAD

**Issue by Phoenix202020** [SIMBAChain/simbachain-vscode-extension#6]
Reported at security@simbachain.com

**Comment by Phoenix202020** [comment]
any update on this?

**Comment by keyz182** [comment]
We utilise a 3rd party (Auth0) for authentication. We are contacting them about the issue. Thanks.

**Comment by keyz182** [comment]
@Phoenix202020 SMS account recovery is not enabled for our system, so this should not be possible. Can you please contact security@simbachain.com with details of the accounts used (specifically, the email address for the dummy account), and steps to recreate.

**Comment by Phoenix202020** [comment]
@keyz182 Hi Kieran, I am sorry for sending you a wrong report. The bug on simba chain is a bit different but that is also high severity as it is also an account takeover.

I am reporting you now at security@simbachain.com
